### PR TITLE
Main into Swing

### PR DESCRIPTION
**Pull request by klokailo**

### CODE REVIEW

**Review by nanogotalk — APPROVED** [review]
I think everything is fine, thank you for your job!

**Review by Lftw — COMMENTED** [review]
So if I understood correctly, we will use the same branch swing but this main branch is to facilitate linking the backend to the frontend?

**Comment by klokailo** [comment]
Yes, thank you for the review @Lftw

**Review by xinlei55555 — APPROVED** [review]
Thank you Kai for this pull request, it will be greatly useful to the integration of the game logic with the frontend

**Comment by Lftw** [comment]
Amazing I am approving

**Review by Lftw — APPROVED** [review]

**Pull request merged**
