### PR TITLE
Backend Base

### PR DESCRIPTION
**Pull request by klokailo**
# Goal
We aim to allocate game servers dynamically within a K8s cluster using Agones.

Our basic principals are these:
- Each game match (or "room") is managed by a single gameserver instance
- Each client creates its own UUID that it uses in all interactions
- Every service we have is stateless, and we use in-memory Redis to store all stateful information.

# Implementation 

This is done with four major components:
## Matchmaker
A springboot app that communicates directly with agones. 
- First point of contact for clients before they enter a room
- Has three (subject to change of course) different endpoints:
  - `/create-game`: First attempts to pull a "Ready" (not-in-use) gameserver from our fleet, apply a `GameServerAllocation` (Agones CRD) to assign it, then does the same actions as `/join-game`
  - `/join-game`: Attempts to join a gameserver (room) that already exists. 
  - `/leave-game`: Terminates client session with gameserver, notifies the gameserver of client departure.
- Whenever a player has joined a gameserver, we store their session data in redis.
- The matchmaker is itself stateless and can be scaled dynamically using `HorizontalPodAutoscaler`.
- This service communicates with the Agones Allocator Service using a GRPC wrapper to grab un-allocated instances when needed.
- This service also receives periodic requests from the Agones Controller Service on its `/autoscale` endpoint to determine how many gameserver instances we should have in our fleet.

## Gameserver
Another springboot app that communicates directly with clients once they are in a game.
- This is represented internally using the Agones `GameServer` CRD.
  - This way, we can have multiple `gameserver`s in a single Agones Fleet (another CRD).
  - Our game server also reports health and readiness checks to the Agones controller.
  - Has two main states: Available (not in use), and Allocated (players active). 
- We create client connections using spring websockets.
  - We have a custom packet schema declared using Protobuf, and we serialize this to raw binary 
    - Potentially a task could be to change this to use GRPC? But I think that is overkill
  - Upon receiving a packet we fire a springboot ApplicationEvent that can be handled anywhere within the application.
    - This makes writing game logic (which is non-existant) very straightforward.
- Anytime a player is connect to a gameserver they must have a session stored in redis.
- Autoscaled by Agones with custom logic in Matchmaker.

## Redis
Within the same K8s cluster we have a basic in-memory Redis database setup.

This stores two things:
- Anytime a client is connected to a gameserver, we store key `session:CLIENT_ID` with value `GAME_SERVER_NAME`.
  - Small note on the internals of this: Currently game server names are just their K8s assigned resource name (so like `spydle-fleet-12345-abcdef`) and not their room ID (which doesn't have logic for it yet).
- We also store in key `gameserver:GAME_SERVER_NAME` the following values:
  - Room ID
  - IP and port
  - GameState (Waiting, Playing, Ending)
  - Public (boolean, can other people join)

## Deployment
We use a kustomize stack for deploying everything in a K8s cluster. Currently we are using minikube for its simplicity but may change to k3s, microk8s or kubeadm.

The deployment stack has the following components:
- `/base`: The default resources we should stack first
  - `/base/agones`: Static templated helm chart for installing agones in its own namespace, `agones-system`. 
    - Has some custom configuration to modify MTLS settings and change GRPC ports for the allocator service.
  - `/base/gameserver`: Resources for deploying our gameserver fleet and autoscaler.
  - `/base/matchmaker`: Resources for deploying our matchmaker service.
  - `/base/ingress`: Resources for deploying the NGINX ingress server that will sit in front of matchmaker.
  - `/base/redis`: Resources for deploying our redis database.
- `/env/dev`: Additional set of patches for modifying the stack for a dev/pre-prod environment.
  - All this does currently is decrease the minimum number of replicas for all our services.
- `/env/prd`: Additional set of patches for modifying the stack for a production environment.
  - Currently does nothing.

# TODO
- There are many TODO stubs left in the code. Some represent logic that is missing, while others indicate places where we can begin writing actual game logic.
- Write the word game logic:
  - Finish the protobuf packet schema for gameserver/client communication
  - Use the ApplicationEvent system to handle packets coming from clients
- We currently have zero testing:
  - Write unit tests for everything using Mockito
  - Write functional tests for the K8s cluster
    - Depending on how implemented, this could be a ton of work. Not sure if we need it.
  - Write E2E tests for K8s
    - This could also be a ton of work. Potentially could use the e2e test framework for k8s but this would require a lot of golang boilerplate.
- We need more javadocs for everything
- We are not following CA or SOLID very closely (yet!)
  - With springboot it shouldn't be too hard to change everything to CA principles.

## Other Smaller Items
- Missing LetsEncrypt certs for the domain totallyspies.dev
  - We should have TLS for all incoming requests
  - However, within the cluster I am not confident that it is worth the effort of doing MTLS for service-to-service communication. Its just a massive pain.
    - But if we did do it, we could use Istio.
- Missing much of the K8s ecosystem tools (metrics & observability)
  - Will install grafana for extremely basic logging and metrics.

### CODE REVIEW

**Review by xinlei55555 — COMMENTED** [review]
lgtm

**Review by xinlei55555 — APPROVED** [review]
lgtm

**Review by xinlei55555 — APPROVED** [review]

**Review by xinlei55555 — COMMENTED** [review]
lgtm lgtm lgtm

**Review by xinlei55555 — APPROVED** [review]

**Review by chopikus — APPROVED** [review]
I approve

**Review by xinlei55555 — APPROVED** [review]
lgtm

**Review by xinlei55555 — APPROVED** [review]
This is a great Pull Request Kai, I wish you the best in your future endeavours

**Pull request merged**
