### PR TITLE
Improved Clean Architecture Output Boundaries

### PR DESCRIPTION
**Pull request by klokailo**
- Fixed un-implemented output boundaries for some usecases
- Used lazy dependency injection in spring boot to avoid dependency loops between controllers and presenters
  - Removed some spring application events that are unnecessary because of this

### CODE REVIEW

**Review by xinlei55555 — COMMENTED** [review]
Great implementation to avoid dependency loops. I was just wondering what is the @Lazy decorator, and how is it used here?
Good idea, we almost forgot to implement the boundaries

**Comment by chopikus** [comment]
Which spring application events did we remove? Is it a guesswordevent?

**Comment by klokailo** [comment]
The `@Lazy` annotation modifies Spring Boot's behaviour when injecting bean dependencies into our class.

Typically, when spring starts up our application, it figures out which beans depend on which other beans, and builds a dependency tree from this. Then, it loads the classes at the bottom of the tree first, so that we are confident that we have the necessary beans to inject already loaded into the application context once we are initializing each bean.

The problem with this is that if you have two beans, Bean A and Bean B, where A depends on B and also B depends on A, then we have a dependency loop! We cannot load one before the other, because one of them is guaranteed to fail.
This dependency loop is actually enforced by default in Clean Architecture: Views depend on Controllers which depend on Use Case Interactors which depend on Presenters which depend on Views. This is bad!

The way we can fix this, is by marking one of the dependencies in this chain as "Lazy", specifically, I have marked the Use Case Interactor's dependency on Presenters as "Lazy". 
What this does, is that it tells spring boot "When you are initializing the Interactor beans, don't try to initialize the Presenter beans first. Instead, just set the value to `null`, and you can inject this bean into the class whenever the Presenter has been initalized".

This avoids our dependency loop, and allows us to keep clean architecture properly implement in our project.

(Thinking about it further, dependency loops are generally bad practice and not advised that you do this hacky behaviour with the Lazy decorator. So if Clean Architecture as a pattern, *forces* us to have a dependency loop, is it all that great? I think that there are better options)

**Review by xinlei55555 — APPROVED** [review]
Oh! I see, so it creates those singletons on start, but creates the lazy ones afterwards, to avoid dependency issues!
Thank you for the explanation, 
Approved.

**Pull request merged**
