### PR TITLE
[Draft] Game logic #2

### PR DESCRIPTION
**Pull request by chopikus**
### Updates already implemented
* First e2e test is implemented (manual for now)
* Now you can specify total game time with the `SbStartGame` message. By default it's 1 minute.
* Fix for multiple starts of the game
* Check that input is a valid word
* Generates a real substring
* sends update player list anytime someone joins/leaves/updates the score
* sends the scoreboard when the game is finished

1. Anyone can start a game by sending `SbStartGame` message, **specifying the game time** (from 5 seconds to 1000 seconds). Once the game starts everyone receives a `CbNewTurn` message; the timer starts to tick.
2. On a turn, the selected player has to input a word that has includes a current substring. If a player sends an `SbGuess` message with such a word, that player gets points equal to the number of characters in a word, and a new turn is made.
3. Every second all players get an update on how much time is left till the end of the game.
4. Once the timer ends, the server sends an `SbEndGame` message with a list of all players **sorted by score, descending**.

### Things that need to be fixed/updated in the next PR

* lives are not counted
* no time limit for entering a word
* what if 2 players have the same score

### CODE REVIEW

**Comment by chopikus** [comment]
Right now the player scores are wrong; e2e test produces an exception.

Following code breaks:
```
  @EventListener(SessionOpenEvent.class)
    public void onSessionOpen() {
        // TODO: Update game server state (possibly need gameServerConfiguration?)
        broadcastPlayers();
    }
```

Logs:
```
java.lang.IllegalStateException: The remote endpoint was in state [BINARY_PARTIAL_WRITING] which is an invalid state for called method
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.checkState(WsRemoteEndpointImplBase.java:1250) ~[tomcat-embed-websocket-10.1.31.jar:10.1.31]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.binaryPartialStart(WsRemoteEndpointImplBase.java:1205) ~[tomcat-embed-websocket-10.1.31.jar:10.1.31]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialBytes(WsRemoteEndpointImplBase.java:163) ~[tomcat-embed-websocket-10.1.31.jar:10.1.31]
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendBinary(WsRemoteEndpointBasic.java:54) ~[tomcat-embed-websocket-10.1.31.jar:10.1.31]
	at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendBinaryMessage(StandardWebSocketSession.java:222) ~[spring-websocket-6.1.14.jar:6.1.14]
	at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:111) ~[spring-websocket-6.1.14.jar:6.1.14]
	at dev.totallyspies.spydle.gameserver.message.GameSocketHandler.sendCbMessage(GameSocketHandler.java:96) ~[main/:na]
	at dev.totallyspies.spydle.gameserver.message.GameSocketHandler.broadcastCbMessage(GameSocketHandler.java:105) ~[main/:na]
	at dev.totallyspies.spydle.gameserver.game.GameLogicEvents.broadcastPlayers(GameLogicEvents.java:117) ~[main/:na]
	at dev.totallyspies.spydle.gameserver.game.GameLogicEvents.onSessionOpen(GameLogicEvents.java:38) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:569) ~[na:na]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:365) ~[spring-context-6.1.14.jar:6.1.14]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:237) ~[spring-context-6.1.14.jar:6.1.14]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:168) ~[spring-context-6.1.14.jar:6.1.14]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185) ~[spring-context-6.1.14.jar:6.1.14]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178) ~[spring-context-6.1.14.jar:6.1.14]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156) ~[spring-context-6.1.14.jar:6.1.14]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:452) ~[spring-context-6.1.14.jar:6.1.14]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:385) ~[spring-context-6.1.14.jar:6.1.14]
	at dev.totallyspies.spydle.gameserver.message.GameSocketHandler.afterConnectionEstablished(GameSocketHandler.java:147) ~[main/:na]
	at org.springframework.web.socket.handler.WebSocketHandlerDecorator.afterConnectionEstablished(WebSocketHandlerDecorator.java:70) ~[spring-websocket-6.1.14.jar:6.1.14]
	at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.afterConnectionEstablished(LoggingWebSocketHandlerDecorator.java:48) ~[spring-websocket-6.1.14.jar:6.1.14]
	at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.afterConnectionEstablished(ExceptionWebSocketHandlerDecorator.java:48) ~[spring-websocket-6.1.14.jar:6.1.14]
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.onOpen(StandardWebSocketHandlerAdapter.java:103) ~[spring-websocket-6.1.14.jar:6.1.14]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:131) ~[tomcat-embed-websocket-10.1.31.jar:10.1.31]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:947) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.31.jar:10.1.31]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
```

**Comment by chopikus** [comment]
@klokailo please look at this exception
Also, maybe we should make gameSocketHandler not throw any exceptions. Right now the game logic updates are wrong if one of gameSocketHandler calls fails

**Comment by chopikus** [comment]
@klokailo are you sure we need to wait until the `WebSocketSession` is open? The doc for `WebSocketHandler#afterConnectionEstablished` says it's invoke after 'WebSocket negotiation has succeeded and the WebSocket connection is opened and ready for use'.

I think websocketsession is open by the time afterConnectionEstablished is called.

**Comment by chopikus** [comment]
@klokailo Please look into this
`ClientSocketHandler` gets stuck on `open`, specifically at .get() on line 59: `session = client.execute(this, headers, uri).get();`

**Comment by chopikus** [comment]
I think we hit a deadlock, when I remove `synchronized` from open method in `ClientSocketHandler`, sockets open (but fail to send a SbMessage later)

https://docs.oracle.com/javase/tutorial/essential/concurrency/deadlock.html

**Comment by chopikus** [comment]
There is a new folder 'words' with a class that generates substrings and a file 'words.txt'. 
For each substring it counts the number of words that have that substring. It outputs a file substrings.csv.

Setup:
1. `java SubstringGenerator.java > substrings.csv`;
2. copy words.txt and substrings.csv to resources folder of the gameServer

Game logic reads words.txt and substrings.csv from resources folder, takes substrings that are contained in at least 1000 words from the dictionary, generates a random substring. Only valid words are allowed

'words.txt' has words from the official Scrabble game and contains ~300000 words. There are roughly 700 substrings available to pick from if the threshold is 1000. We can change the threshold to change difficulty of the game

**Review by klokailo — APPROVED** [review]

**Pull request merged**
