### PR TITLE
Swing Restructure and add as Gradle Submodule

### PR DESCRIPTION
**Pull request by klokailo**
## This PR
- Adds proper package format for swing classes
  - Source folder `src/main/java`
  - Package `dev.totallyspies.spydle.frontend`
- Updates some class names to use proper java camel case
- Adds this project as a gradle submodule of the root project
  - This is necessary and useful because it will allow this frontend project to access the shared protoc generated files for game messages that are in the `shared` gradle module.

## IMPORTANT
This means that once this PR is merged, you can only open the root project directory in your IntelliJ for it to load properly. Opening the just `frontend` folder will not work.

### CODE REVIEW

**Comment by klokailo** [comment]
@xinlei55555 can we get a review here
also is there a reason for us to have all the swing stuff on a swing branch and merge into main? I want to start using frontend stuff and writing the socket logic into there

**Comment by klokailo** [comment]
I am changing the base to main, lets all work off the `main` branch

**Comment by klokailo** [comment]
Changed merge base to swing, rolled-back to before I merged main into this branch. Should be good to go @xinlei55555

**Comment by klokailo** [comment]
I severely screwed up the commit history for this one and now it is entangled with some other branches as well.
We will go over this tomorrow and merge this into main, and then main into swing.

**Review by xinlei55555 — APPROVED** [review]
Thank you for reformatting. Everyone therefore needs to run IntelliJ from the previous folder.

**Comment by nanogotalk** [comment]
It was a really smart idea to add this project as a gradle submodule of the root project, good job !

**Review by Lftw — COMMENTED** [review]
Thank you for the PR! The changes make a lot of sense, especially with the new package structure and the Gradle submodule setup. Organizing the swing classes under dev.totallyspies.spydle.frontend makes it more readable
The integration as a Gradle submodule will be helpful for accessing shared protobuf-generated files

**Review by nanogotalk — APPROVED** [review]

**Review by Lftw — APPROVED** [review]
Thank you for the PR! The changes make a lot of sense, especially with the new package structure and the Gradle submodule setup. Organizing the swing classes under dev.totallyspies.spydle.frontend makes it more readable
The integration as a Gradle submodule will be helpful for accessing shared protobuf-generated files

**Pull request merged**
